### ISSUE TITLE
train_from 从哪里获得？

### ISSUE THREAD

**Issue by shell-nlp** [YiSyuanChen/MTL-ABS#1]
训练阶段
-train_from  ../models/pre_train/pre_ext_abs_cnndm/model_step_148000.pt \       

train_from 从哪里获得？

**Comment by YiSyuanChen** [comment]
Hi, thanks for your interest in our work. Our base model shares the architecture with [PreSumm](https://github.com/nlpyang/PreSumm). You could directly download the [pre-trained model ](https://drive.google.com/file/d/1-IKVCtc4Q-BdZpjXc4s70_fRsWnjtYLr/view)they provided in the repository.
