### ISSUE TITLE
How to construct source corpus and maml's Task set?

### ISSUE THREAD

**Issue by iin729** [YiSyuanChen/MTL-ABS#5]
Hello, author, I am very interested in your innovative work. I have carefully studied your paper and code, and reproduced the score. The effect is remarkable. But regarding the data set required for MAML training in the paper consists of a task set {Ti}，i belongs [1,M], the construction of this set is selected from multiple corpora through a series of criteria, here I have two points of confusion:

Suppose there are four corpora A,B,C,D, A is selected as the target corpus, B,C,D is the source corpus, Ai is the ith article in A

1. How to construct source corpus? Using criterion 1 to construct source corpus's task Ti, who is the target of the specific calculation criterion?
Is it to calculate the scores of each article of B and each article of A, and then sum and average the scores to select the articles with the highest scores?
rank(avg(score{Ai,Bi})) ,select top n Bi in B as source corpus from B?

2. How to construct a task? Is it to aggregate the articles with high scores into one task?
rank(avg(score{Ai,Aj})) ,j != i, selcet top Aj in A as task of Ai ?

Looking forward to your answers, or if you can provide this part of the source code better, thank you very much!

**Comment by YiSyuanChen** [comment]
Hi, I am sorry for accidentally missing this issue for such a long time.

1. The selection is on corpus-level.  In your example, we sample at most 10000 articles for all four corpora, and compute the average scores with the criterion for (A,B), (A,C) and (A,D). We then select top few corpora (e.g. B and D) jointly as our source corpus. 
2.  A task for a corpus consists of data points that are randomly sampled from that corpus.

Although being late, hope this could be helpful. Thank you.

**Comment by iin729** [comment]
Thank you,  I got it.
