### ISSUE TITLE
Decoding lengths

### ISSUE THREAD

**Issue by cylnlp** [YiSyuanChen/MTL-ABS#6]
Hi @YiSyuanChen, sorry for bothering you again.
I wonder how you set the min/max decoding lengths?
I only find the parameters for aeslc in your scripts.
Did you follow PEGASUS to set the max lengths?

Thanks

**Comment by YiSyuanChen** [comment]
Hi,
We set the max/min decoding lengths empirically without carefully tuning. However, for most datasets (other than AESLC), the max decoding length is set to 32/64/128/256 as PEGASUS did.
